all:
  hosts:
    k8s-ha-dev-mn1:
      ansible_host: 192.168.71.32
      ip: 192.168.71.32
      acces_ip: 192.168.71.32
    k8s-ha-dev-mn2:
      ansible_host: 192.168.71.33
      ip: 192.168.71.33
      acces_ip: 192.168.71.33
    k8s-ha-dev-mn3:
      ansible_host: 192.168.50.213
      ip: 192.168.50.213
      acces_ip: 192.168.50.213
    k8s-ha-dev-etcd1:
      ansible_host: 192.168.71.34
      ip: 192.168.71.34
      acces_ip: 192.168.71.34
    k8s-ha-dev-etcd2:
      ansible_host: 192.168.71.35
      ip: 192.168.71.35
      acces_ip: 192.168.71.35
    k8s-ha-dev-etcd3:
      ansible_host: 192.168.71.36
      ip: 192.168.71.36
      acces_ip: 192.168.71.36
    k8s-ha-dev-wn1:
      ansible_host: 192.168.71.37
      ip: 192.168.71.37
      acces_ip: 192.168.71.37
    k8s-ha-dev-wn2:
      ansible_host: 192.168.71.38
      ip: 192.168.71.38
      acces_ip: 192.168.71.38
    k8s-ha-dev-wn3:
      ansible_host: 192.168.71.39
      ip: 192.168.71.39
      acces_ip: 192.168.71.39
    k8s-ha-dev-wn4:
      ansible_host: 192.168.50.214
      ip: 192.168.50.214
      acces_ip: 192.168.50.214
  children:
    kube-master:
      hosts:
        k8s-ha-dev-mn1:
        k8s-ha-dev-mn2:
        k8s-ha-dev-mn3:
    kube-node:
      hosts:
        k8s-ha-dev-wn1:
        k8s-ha-dev-wn2:
        k8s-ha-dev-wn3:
        k8s-ha-dev-wn4:
    etcd:
      hosts:
        k8s-ha-dev-etcd1:
        k8s-ha-dev-etcd2:
        k8s-ha-dev-etcd3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: { }
